### ISSUE TITLE
Using react-modal in custom _app.js in prod build results in server crash when deployed to Firebase

### ISSUE THREAD

**Issue by shankie-san** [jthegedus/firebase-gcp-examples#106] opened 2020-06-02 20:27 UTC
## Which Package & Your Environment

* Package in this repo: nextjs
* OS: n/a
* Node Version: 10
* Pkg Manager: npm
* Shell: zsh

## Expected Behaviour

Using `react-modal` in a custom `_app.js` should work the same on Firebase server as it does with local dev

## Actual Behaviour

Using `react-modal` in custom `_app.js` results in a `Error: Cannot find module 'react-modal'"`

I've posted this already [here](https://github.com/vercel/next.js/discussions/13675), but after some digging, I think that the issue is with the setup here because the production Next code generated by `next build && next serve` works fine (in addition to `next dev` working fine) – it only fails when deploying to the cloud function.

Here's the original issue I posted on NextJS:

I'm using a custom `_app.js` because I want to have a `<AuthContextProvider />` available to all my components. This both provides a `user` to every component that uses that context, but also a `doLogin` method that opens a `react-modal` to handle a user login with my auth provider.

```javascript
import { AuthContextProvider } from "../components/context/AuthContext";

const App = ({ Component, pageProps }) => {
  return (
    <AuthContextProvider>
      <Component {...pageProps} />
    </AuthContextProvider>
  );
};
```

Nothing too controversial.

The provider looks something like this (redacted a bit for brevity):

```javascript
import Modal from "react-modal";
export const AuthContextProvider = ({ children }) => {
 ...
  return (
    <AuthContext.Provider
      value={{
        user,
        doLogin,
      }}
    >
      <Modal
        isOpen={loginModalIsOpen && !isFullUser}
        onRequestClose={() => setLoginModalIsOpen(false)}
        contentLabel="Log in"
      >
        <h1>Log in</h1>
        <Login />
      </Modal>
      {user ? children : <Loading />}
    </AuthContext.Provider>
  );
};
```

This all works fine in local dev (Mac), but on the server (Firebase cloud function – presumably in production mode), any time I import `react-modal` in a file included in the custom `_app.js`, I get `Error: Cannot find module 'react-modal'"`. 

This *doesn't* happen if I include `react-modal` in one of my Next page components – only if I include it in `_app.js`, so I'm assuming that it's not an environment-related problem. 

## Context

This is an issue because I want to be able to use `react-modal` in context and custom hooks

**Comment by jthegedus** [comment] 2020-06-03 03:34
Are you able to provide a repo with a minimum reproduction that shows this error? EG: clone this example, add the minimum amount of code that produces this error.

**Comment by shankie-san** [comment] 2020-06-08 14:54
Thanks for your reply @jthegedus . I spent this morning producing a minimal replica and all was fine. After many more hours of trial and error with my live project (including deploying my minimal code live and vice versa), I deleted the cloud function and repdeployed. And all was fine 🤦 

Sooooo... I guess the question is, since there is obviously some caching (including of Next outputs), do you know any way of invalidating the cache on deploy or similar?

**Comment by jthegedus** [comment] 2020-06-09 02:26
Glad it is working for you now.

Re caching: yes, Next.js sets the `s-maxage` cache control on a number of page responses which Firebase Hosting uses to tell the CDN the duration to cache that resource. The cache settings are different in dev mode and you wouldn't see them running the prod build locally as they don't go through a CDN.

Firebase don't document much of their cache flushing mechanisms, but Next.js builds each `next build` with a new UUID in the path for the assets for `_app.js` etc. So each new deployment should serve you the correct files. For good measure, I usually run `rimraf .nextjs` (or on `distDir` defined in `next.config.js`) in an `npm` `prebuild` script. See the `functions-nextjs` example. It is possible your browser cached client was requesting an older build from the server and it serving these files if they were all contained in the deployed build output. A hard refresh of your browser should have resolved this though.

**Comment by jthegedus** [comment] 2020-06-09 02:28
Given there's no longer an issue I will close this. Feel free to continue the discussion here should you have any further queries, open a new issue for new topics or reopen if you identify something within the latest example that causes this initial issue :smile:

**Closed by jthegedus** 2020-06-09 02:28 UTC

**Comment by shankie-san** [comment] 2020-06-09 14:04
Thanks for your input @jthegedus – interesting food for thought.

Re: cache – I don't think that this was an issue with statically rendered pages being cached as it was causing the cloud function to crash with `internal server error` – meaning that it was something to do with SSR. To me, it feels like _my_ code was getting updated, but the dependencies weren't getting updated. Is it possible that the cloud function has two separate bundles like webpack does on the client, like `app.bundle.js` and `vendor.bundle.js` – but in this case, the app was being cache-busted using UUIDs (such as `app.123ir232i32sklfjhs.js`) but the `vendor.bundle.js` wasn't? Maybe it ended up in a cached volume or something? I don't know!

And yes, the issues is definitely closed! I'm just scratching my head about firebase internals 😊

**Comment by jthegedus** [comment] 2020-06-09 23:02
>I don't think that this was an issue with statically rendered pages being cached as it was causing the cloud function to crash with `internal server error`

Next.js's internal runtime files and `_app.js` etc are also served from the Cloud Function the first time they are requested, so it's possible some request was trying to load a file that was no longer present or an older file that was still present. Again, Next.js uses it's build folder for storing `dev` files as well as each `next build` output, so it's crucial to clear this directory, then do a final `next build` and then upload to Firebase, otherwise older `next build` files will be uploaded to Firebase Cloud Function.

As for Cloud Functions themselves, there's no real magic about what code ends up there or special caching. The contents of the Dir you send is what is in the Cloud Function. If you go to the GCP Console for Cloud Functions you can download the entire contents of the function as a Zip and browse what code was sent to investigate further.

I suspect this is a situation where you had multiple `next build` outputs on your server and an old client in your browser that requested the old files, and instead of erroring because it couldn't find them got into a bad state. It's hard to say.

Additionally, due to the nature of Cloud Functions, sometimes it takes a couple minutes for the new code to be served, however it this is rare and is _almost always_ available after `firebase deploy` has finished.
